### ISSUE TITLE
[macOS] falign-loops=32' is not supported

### ISSUE THREAD

**Issue by hiroyuki-sato** [ARM-software/progress64#10]
Hi,

I got the following warnings on macOS.

* ProductName:	Mac OS X
* ProductVersion:	10.15.5
* BuildVersion:	19F101
* clang: Apple clang version 11.0.3 (clang-1103.0.32.62)
* Progress64: bfe9ae773ab39f682d6ea3fac96bdc7a85c03334

```
clang: warning: optimization flag '-falign-loops=32' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-jumps=32' is not supported [-Wignored-optimization-argument]
```

It seems that the following change fix the warning.

```diff
diff --git a/Makefile b/Makefile
index cde6702..5aa29a5 100644
--- a/Makefile
+++ b/Makefile
@@ -89,7 +89,10 @@ CCFLAGS += -march=armv8.1-a+lse -D__ARM_FEATURE_ATOMICS
 endif
 CCFLAGS += -g -ggdb -Wall -Wextra
 CCFLAGS += -fomit-frame-pointer
-CCFLAGS += -falign-loops=32 -falign-jumps=32 -falign-functions=32
+ifneq ($(UNAME),Darwin)
+CCFLAGS += -falign-loops=32 -falign-jumps=32
+endif
+CCFLAGS += -falign-functions=32
 CCFLAGS += -fstrict-aliasing -fno-stack-check -fno-stack-protector
 LDFLAGS += -g -ggdb -pthread
```

**Comment by WonderfulVoid** [comment]
Yes, LLVM doesn't recognize -falign-loops and -falign-jumps options (and some versions also seem not to recognize -falign-functions). I will fix this.

**Comment by WonderfulVoid** [comment]
Fixed in https://github.com/ARM-software/progress64/commit/3093d103b8cf6ee89d8d36abfcea068c4d736b2b and https://github.com/ARM-software/progress64/commit/cda0b9722e9399ebbcdb6de3c54609abf0c66076.

**Comment by hiroyuki-sato** [comment]
Thank you!
