### ISSUE TITLE
OS abstractions of `syscall` deprecated on macOS

### ISSUE THREAD

**Issue by nxrighthere** [ARM-software/progress64#8]
Just noticed that abstracted `syscall()` functionality is deprecated on macOS. Suggested alternative to get a thread ID is `pthread_threadid_np()`.

**Comment by WonderfulVoid** [comment]
pthread_threadid_np() is used on macOS, this was changed in commit https://github.com/ARM-software/progress64/commit/3ebdd9119d9cf1b2ef32fc788d8ed0a189b97620

**Comment by nxrighthere** [comment]
Oh, sorry, haven't noticed that... Just forgot to update my fork before opening the issue. 🤕
